#!/usr/bin/env swift

# SwiftLint Configuration pour Soirées Swipe UI
# Version 1.0 - Optimisée pour SwiftUI et architecture MVVM

# Fichiers et répertoires à inclure dans le linting
included:
  - Sources
  - Tests

# Fichiers et répertoires à exclure du linting
excluded:
  - Sources/SoireesUI/Resources
  - .build
  - DerivedData
  - Package.swift

# Règles désactivées globalement
disabled_rules:
  - trailing_whitespace # Géré par l'éditeur
  - todo # Les TODOs sont acceptés en développement
  - line_length # Géré par les règles custom ci-dessous

# Règles activées en plus des règles par défaut
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - strong_iboutlet
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Configuration des règles
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 8
  error: 15

nesting:
  type_level:
    warning: 3
    error: 5
  function_level:
    warning: 3
    error: 5

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

# Configuration pour les règles opt-in
attributes:
  always_on_same_line:
    - "@objc"
    - "@IBAction"
    - "@IBOutlet"
    - "@NSManaged"
    - "@Published"
    - "@State"
    - "@StateObject"
    - "@ObservedObject"
    - "@EnvironmentObject"
    - "@Environment"
    - "@Binding"
    - "@AppStorage"
    - "@SceneStorage"
  always_on_line_above:
    - "@available"
    - "@discardableResult"
    - "@MainActor"

file_header:
  required_pattern: |
                    \/\/
                    \/\/ .*\.swift
                    \/\/ SoireesUI
                    \/\/
                    \/\/ Created.*
                    \/\/

modifier_order:
  preferred_modifier_order:
    - acl
    - setterACL
    - override
    - dynamic
    - mutating
    - lazy
    - final
    - required
    - convenience
    - typeMethods
    - owned

# Configuration spécifique pour SwiftUI
implicit_return:
  included:
    - closure
    - function
    - getter

# Configuration des imports
sorted_imports:
  groups:
    - "SwiftUI"
    - "UIKit"
    - "Foundation"
    - "Combine"
    - "CoreLocation"
    - "MapKit"

# Configuration pour les tests
private_outlet:
  allow_private_set: true

# Messages de warning personnalisés
custom_rules:
  swiftui_view_body_single_statement:
    name: "SwiftUI View Body Single Statement"
    regex: '^(\s*)var body: some View \{\s*$\n(?:\1\s+.*\n)*\1\s+return '
    message: "SwiftUI View body should use implicit return for single statements"
    severity: warning

  swiftui_private_vars_should_be_state:
    name: "SwiftUI Private Variables Should Be @State"
    regex: '^\s*private var [^=]+='
    message: "Private variables in SwiftUI views should typically be @State properties"
    severity: warning

  mark_comment_format:
    name: "MARK Comment Format"
    regex: '^\/\/ MARK: - (?!.*[a-z]$)'
    message: "MARK comments should follow the format: // MARK: - Section Name"
    severity: warning

  todo_format:
    name: "TODO Format"
    regex: '\/\/ TODO(?!:)'
    message: "TODO comments should include a colon: // TODO:"
    severity: warning

  fixme_format:
    name: "FIXME Format"
    regex: '\/\/ FIXME(?!:)'
    message: "FIXME comments should include a colon: // FIXME:"
    severity: warning

# Configuration pour les exclusions spécifiques
force_cast: warning
force_try: warning
force_unwrapping: warning

# Reporter configuration
reporter: "xcode" 